# Generated by Django 4.0 on 2024-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
