# Generated by Django 4.0 on 2024-01-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_agent'),
        ('frontend', '0002_house_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/images/default.jpg', upload_to='houses/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
