# Generated by Django 4.0 on 2024-01-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_house_type_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='frontend.house_type'),
        ),
    ]
