# Generated by Django 4.0 on 2024-01-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_photo_house_delete_house_delete_house_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_location', models.CharField(choices=[('mexico', 'mexico'), ('shiromeda', 'shiromeda'), ('arat kilo', 'arat kilo'), ('amist kilo', 'amist kilo'), ('piassa', 'piassa')], max_length=40)),
                ('house_image', models.ImageField(upload_to='houses/')),
                ('house_bedroom', models.IntegerField()),
                ('house_size_in_feet', models.CharField(max_length=200)),
                ('house_details', models.TextField()),
                ('is_house_with_utensil', models.BooleanField()),
                ('is_house_with_kitchen', models.BooleanField(default='True')),
                ('is_house_reserved', models.BooleanField(default='False')),
                ('house_address', models.CharField(default='ferencay legasion mazoriya', max_length=100)),
                ('fees_in_birr', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='House_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('Icon', models.ImageField(default='default.jpg', upload_to='houses/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='frontend.house_type'),
        ),
    ]
