# Generated by Django 4.0 on 2024-01-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_house_house_type_photo_house_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='house',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='House_type',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
