# Generated by Django 4.0 on 2024-01-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_photo_house_delete_house_delete_house_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('Icon', models.ImageField(default='default.jpg', upload_to='houses/')),
            ],
        ),
    ]
