# Generated by Django 4.0 on 2024-01-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='House_type',
        ),
    ]
