# Generated by Django 4.0 on 2024-01-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_house_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House_type',
        ),
    ]
