# Generated by Django 4.0 on 2024-01-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_agent'),
        ('frontend', '0014_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_location', models.CharField(choices=[('mexico', 'mexico'), ('shiromeda', 'shiromeda'), ('arat kilo', 'arat kilo'), ('amist kilo', 'amist kilo'), ('piassa', 'piassa')], max_length=40)),
                ('house_image', models.ImageField(upload_to='static/img')),
                ('house_bedroom', models.IntegerField()),
                ('house_size_in_feet', models.CharField(max_length=200)),
                ('house_details', models.TextField()),
                ('is_house_with_utensil', models.BooleanField()),
                ('is_house_with_kitchen', models.BooleanField(default='True')),
                ('is_house_reserved', models.BooleanField(default='False')),
                ('house_address', models.CharField(default='ferencay legasion mazoriya', max_length=100)),
                ('fees_in_birr', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='frontend.house_type')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
