# Generated by Django 4.0 on 2024-01-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.house')),
            ],
        ),
    ]
