# Generated by Django 4.0 on 2024-01-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_agent'),
        ('frontend', '0016_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_time_date', models.DateTimeField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.house')),
                ('user_agent', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='agent_schedule', to='core.user')),
                ('user_tenante', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_schedule', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_image', models.ImageField(upload_to='static/img')),
                ('agent_phone_number', models.CharField(default='0000000000', max_length=50)),
                ('agent_workdone', models.IntegerField(default=1)),
                ('user', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
