# Generated by Django 4.0 on 2024-01-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_view_schedule_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
