# Generated by Django 4.2.3 on 2024-01-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_schedule',
            name='review_time_date',
            field=models.CharField(max_length=200),
        ),
    ]
