# Generated by Django 4.0 on 2024-01-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_agent'),
        ('frontend', '0020_alter_view_schedule_review_time_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('viewing_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.view_schedule')),
            ],
        ),
    ]
