# Generated by Django 4.0 on 2024-01-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_schedule',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='view_schedule',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
